import React from "react";
import Container from "react-bootstrap/Container";
import Project from "../Project/Project";
import "./Projects.css";
import exerciseAppPic1 from "../../media/screenshots/random-exercise-app_cropped.jpg";
import exerciseAppPic2 from "../../media/screenshots/random-exercise-app-2_cropped.jpg";
import soundboardAppPic1 from "../../media/screenshots/soundboard_screenshot.png";
import soundboarAppPic2 from "../../media/screenshots/soundboard_mobile_screenshot.png";

const projects = React.forwardRef((props, ref) => (
  <Container fluid ref={ref} id="Projects">
    <h1>Projects</h1>
    <p></p>
    <div className="Projects">
      {" "}
      <Project
        projectTitle="Random Exercise Generator"
        image1={exerciseAppPic1}
        image2={exerciseAppPic2}
        description="This app allows the user to generate a random bodyweight exercise by pressing the spin button.
       Pressing the spin button makes the gifs spin vertically, simmilar to a slot machine. 
       The gifs are generated by making API calls to GIPHY website so different trending gifs can show when the user operates the app.
       App was made with Reactjs, CSS, and GIPHY API.
"
        techUsed="React, CSS, GIPHY API"
        githubLink="https://github.com/mdaniels22/exercise/tree/master/src"
        siteLink="https://react-app-random-exercise.herokuapp.com/"
      />
      <Project
        projectTitle="Soundboard"
        image1={soundboardAppPic1}
        image2={soundboarAppPic2}
        description="This web app works as a soundboard. Clicking on the letter, touching on mobile, will play the assigned sound.
         Its fully responsive and works for both desktop and mobile.
         Tech used was ReactJs and CSS."
        techUsed="React CSS"
        githubLink="https://github.com/mdaniels22/soundboard/tree/master/src"
        siteLink="https://soundboard-react-app.herokuapp.com/"
      />
      <Project
        projectTitle="Project 3"
        image1="https://via.placeholder.com/300x400"
        description="making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
"
        githubLink=""
        siteLink=""
      />
    </div>
  </Container>
));

export default projects;
